### ISSUE TITLE
improved implementation

### ISSUE THREAD

**Issue by stevengj** [fgasdia/Romberg.jl#3]
I posted an implementation on discourse (https://discourse.julialang.org/t/romberg-jl-simple-romberg-integration-in-julia/39313/8?u=stevengj) using Richardson.jl that is much more general (is not restricted to power-of-two sizes) and vastly simpler.   I'm not sure if you would be interested in adopting it here?

**Comment by fgasdia** [comment]
I commented on discourse that I'd be willing to take in the new algorithm here unless most people prefer that it go into NumericalIntegration.jl.

Romberg.jl isn't currently a registered package, so if we decide it should go into NumericalIntegration, there isn't a concern that people looking for a high performance romberg integration routine would accidentally end up using this package instead of the other. I would register this if we decide it should go here.

(@stevengj  Also, I'll move a little slower merging and updating this package than I did your suggestions for ModifiedHankelFunctionsOfOrderOneThird.jl - I'm pretty sure I'm the only user of that other package!)
